server.port: 9000

base.package: music.manager

logging.level.root: WARN
logging.level.org.springframework.web: DEBUG
logging.level.org.springframework.security: DEBUG

#prevent from deleting database
spring.jpa.hibernate.ddl-auto: create-drop
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
