server.port: 9000

base.package: com.ldz

logging.level.root: WARN
logging.level.org.springframework.web: DEBUG
logging.level.org.springframework.security: DEBUG

#prevent from deleting database
spring.jpa.hibernate.ddl-auto: create-drop
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

parser.date-time-format: "dd/MM/yyyy HH:mm:ss"

token.reinitializer:
      intervaltime: 1800000 #30 minutes
      core-pool-size: 4 #pool size for deletions