server.port: 9000

base.package: music.manager

logging.level.root: WARN
logging.level.org.springframework.web: DEBUG
logging.level.org.springframework.security: DEBUG


spring.datasource.jdbc-url: jdbc:h2:file:./data/music-manager;
spring.datasource.url: jdbc:h2:file:./data/music-manager;

spring.jpa.database: H2
spring.jpa.show-sql: true

#prevent from deleting database
spring.jpa.hibernate.ddl-auto: update

spring.h2.console.enabled: true
spring.h2.console.path: /console
